# fly.toml for production controller
app = 'agent-controller'
primary_region = 'iad'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[build]
  dockerfile = "Dockerfile.controller"

[env]
  PORT = "8080"
  # Controller configuration
  MAX_CONCURRENT_REQUESTS = "100"
  REQUEST_TIMEOUT = "60"
  CACHE_TTL = "60"

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

  [[services.http_checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

# Scale based on load
[[services.autoscale]]
  min_machines_running = 1
  max_machines_running = 10
  hard_limit = 95
  soft_limit = 80

[[vm]]
  memory = '2gb'  # More memory for handling many connections
  cpu_kind = 'shared'
  cpus = 2

# Attach Redis for distributed state
[experimental]
  auto_rollback = true